CREATE TABLE kickstart (
	id_num int NOT NULL PRIMARY KEY,
	campaign varchar(255),
	specific_category varchar(255),
	main_category varchar(255),
	currency varchar(50),
	deadline date,
	goal float,
	launched timestamp,
	pledged float,
	campaign_state varchar(50),
	backers int,
	country varchar(100),
	usd_pledged float,
	usd_pledged_real float,
	usd_goal_real float);
